trigger:
  - main

pool:
  name: Self-hosted

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'
    includePreviewVersions: true

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Project'

- script: dotnet pack --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Pack NuGet Package'

- task: NuGetCommand@2
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishVstsFeed: 'schaud91'
